#!/bin/bash

# dotfiles repository
REPOSITORY=shigasy/dotfiles

DOTDIR=$HOME/.dotfiles

# install package manager
# macであり、 and type brew が実行出来なかったら
if [[ $(uname) == 'Darwin' && ! -x $(type brew > /dev/null 2>&1) ]]; then
  echo "Installing HomeBrew...."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install zsh
fi

# macであり、 and type git が実行出来なかったら 出力は捨てる
# Download repository
echo "Downloading dotfiles...."
if [[ $(uname) == 'Darwin' && ! -x $(type git > /dev/null 2>&1) ]] ; then
  brew install git 2> /dev/null
fi

git clone --recursive https://github.com/$REPOSITORY.git $DOTDIR

ln -s $DOTDIR/zsh/.zshenv $HOME/.zshenv
ln -s $DOTDIR/git/.gitconfig $HOME/.gitconfig

ln -s $DOTDIR/tig/.tigrc $HOME/.tigrc

# symboliclink prompt file
ln -s $DOTDIR/zsh/prompt_ayatk_setup $DOTDIR/zsh/.zprezto/modules/prompt/functions/prompt_ayatk_setup

# vim
ln -s $DOTDIR/vim/vimrc $HOME/.vimrc

# brew install
echo "Installing package...."
cat $DOTDIR/brew | while read package
do
  brew install $package
done

# cask install
echo "Installing macOS apps...."
cat $DOTDIR/cask | while read app
do
  brew cask install $app
done


# sh -c とは
## cmdstring をシェルの入力行であるかのように実行し、次に終了 します。これは、単一コマンドのためにシェルを呼び出す プログラム (例えば、エディター) によって使用されます。

# change shell
# /etc/shelss とは 
## ログインシェルにできるプログラムをフルパスで記述する。ここに登録されていないプログラムをログインシェルにすることはできない。
sudo sh -c 'echo "/usr/local/bin/zsh" >> /etc/shells'
# ログインshell 切り替え
sudo chsh -s /usr/local/bin/zsh
