#!/bin/bash

TMP_FILE=/tmp/dotfiles.tar.gz
# dotfiles repository
REPOSITORY=mypozi/dotfiles

DIR=$(cd $(dirname $0); pwd)
DOTDIR=$HOME/.dotfiles

# install package manager
if [[ $(uname) == 'Darwin' && ! -x $(type brew > /dev/null 2>&1) ]]; then
  echo "Installing HomeBrew...."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install zsh
fi

# Download repository
echo "Downloading dotfiles...."
if [[ $(uname) == 'Darwin' && ! -x $(type git > /dev/null 2>&1) ]] ; then
  brew install git 2> /dev/null
fi

git clone --recursive https://github.com/$REPOSITORY.git $DOTDIR

ln -s $DOTDIR/zsh/.zshenv $HOME/.zshenv
ln -s $DOTDIR/git/.gitconfig $HOME/.gitconfig

# symboliclink prompt file
ln -s $DOTDIR/zsh/prompt_ayatk_setup $DOTDIR/zsh/.zprezto/modules/prompt/functions/prompt_ayatk_setup

# vim
ln -s $DOTDIR/vim/vimrc $HOME/.vimrc

# brew install
echo "Installing package...."
cat ./brew | while read package
do
  echo $package
done

# cask install
echo "Installing macOS apps...."
cat ./cask | while read app
do
  echo $app
done

# change shell
sudo sh -c 'echo "/usr/local/bin/zsh" >> /etc/shells'
sudo chsh -s /usr/local/bin/zsh
