"----------------------------------------------------
" vimrc
"----------------------------------------------------

" init scripts
runtime! init/*.vim

" plugin scripts
runtime! plugin/*.vim

" 矢印キーを無効にする
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

inoremap <C-e> <Esc>$a
inoremap <C-a> <Esc>^i
noremap <C-e> <Esc>$a
noremap <C-a> <Esc>^i
noremap <C-h> ^
noremap <C-l> $
